- hosts: 127.0.0.1
  connection: local
  vars_files:
    - /root/dest/ansible_variables.yml
  roles:
    - base
    - ruby
    - intake
    - { role: omsa, when: ansible_system_vendor == 'Dell Inc.' }