- get_url: url=http://download.opensuse.org/repositories/home:vbernat/CentOS_CentOS-6/home:vbernat.repo dest=/etc/yum.repos.d/vbernat.repo mode=0644 owner=root group=root

- copy: src=sl.repo dest=/etc/yum.repos.d/sl.repo owner=root group=root mode=0644

- command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- shell: yum clean all

- yum: name={{ item }} state=latest
  with_items:
    - lshw
    - lldpd
    
- shell: /usr/sbin/lshw -quiet -xml > /tmp/it-lshw-report.xml creates=/tmp/it-lshw-report.xml

- shell: /usr/sbin/lldpctl -f xml > /tmp/it-lldp-report.xml creates=/tmp/it-lldp-report.xml

- file: path=/var/db owner=root group=root mode=0755 state=directory  

- template: src=collins.yml.j2 dest=/var/db/collins.yml mode=0644