- get_url: url=http://download.opensuse.org/repositories/home:vbernat/CentOS_CentOS-6/home:vbernat.repo dest=/etc/yum.repos.d/vbernat.repo mode=0644 owner=root group=root

- get_url: url=http://ipmiutil.sourceforge.net/FILES/ipmiutil-2.9.3-1_rhel6.x86_64.rpm dest=/tmp/ipmiutil.rpm mode=0644 owner=root group=root

- command: /bin/rpm -ihv /tmp/ipmiutil.rpm

- command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- yum: name={{ item }} state=latest
  with_items:
    - lshw
    - lldpd
    - ruby
    - gem
    
- shell: /usr/sbin/lshw > /tmp/it-lshw-report.xml creates=/tmp/it-lshw-report.xml

- shell: /usr/sbin/lldpctl > /tmp/it-lldp-report.xml creates=/tmp/it-lldp-report.xml

- file: path=/var/db owner=root group=root mode=0755 state=directory  

- template: src=collins.yml.j2 dest=/var/db/collins.yml mode=0644

- gem: name=collins_auth state=latest

- copy: src=intake.rb dest=/var/db/intake.rb owner=root group=root mode=0755

- shell: /var/db/intake.rb creates=/var/db/intake.lock