- yum: name={{ item }} state=latest
  with_items:
    - lshw
    - lldpd
    - ruby
    - gem
    
- shell: /usr/sbin/lshw > /tmp/it-lshw-report.xml creates=/tmp/it-lshw-report.xml

- shell: /usr/sbin/lldpctl > /tmp/it-lldp-report.xml creates=/tmp/it-lldp-report.xml

- file: path=/var/db owner=root group=root mode=0755 state=directory  

- template: src=collins.yml.j2 dest=/var/db/collins.yml mode=0644

- gem: name=collins_auth state=latest